### ISSUE TITLE
A .sut file can't be extracted

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [Loperamide/CSPExtract#2]
OS: Ubuntu 20.04 LTS
Python version: 3.8.10
File tested: "HIMOG modified.sut" from [this brush bundle](https://colodraws.gumroad.com/l/ntnho)
Command used:
`python3 extract.py ./a`
(.sut file is in the folder "a", and the folder "a" is in the same folder as the script)

Terminal output:
```
HIMOG modified.sut
HIMOG modified.sut
Traceback (most recent call last):
  File "extract.py", line 71, in <module>
    main()
  File "extract.py", line 68, in main
    extract_sqlite_layers(sys.argv[1]+"/"+m_file)
  File "extract.py", line 46, in extract_sqlite_layers
    cur.execute("select _PW_ID, FileData from MaterialFile")
sqlite3.OperationalError: no such table: MaterialFile
```

**Comment by Loperamide** [comment]
I dont think a 'sut' file is the same as a CSP file...
It also is a SQLite database, but not with the same tablenames.
Didn't find any image in any table...

**Comment by Loperamide** [comment]
Some of the sut files in the pack have this table, but not all... Another strange brush format 😅
